### PR TITLE
Rebase on tharsis/ethermint v0.11.0

### PR DESCRIPTION
**Pull request by jbowen93**
This PR reverts the previous commit https://github.com/celestiaorg/ethermint/commit/46570120923de036a159106f84ca21b528429166 and rebases on the upstream tharsis/ethermint v0.11.0 release https://github.com/tharsis/ethermint/releases/tag/v0.11.0

When merged this PR will serve as the basis for cutting a v0.11.0+0.1.0 release. See https://github.com/celestiaorg/ethermint/issues/3

Evmos image [ghcr.io/celestiaorg/evmos:ethermint-99db340](https://github.com/celestiaorg/evmos/pkgs/container/evmos/17275290?tag=ethermint-99db340) was built using this change and a manual run of 
```
MODE=rpc HOST=http://127.0.0.1:8545 go test ./tests/rpc/...
```
passed against an ephemeral-cluster using this image.

### CODE REVIEW

**Comment by jbowen93** [comment]
Note that some CI things will fail due to their config issues (Pull Request Labeler, Semgrep, Gosec, etc.)and integration tests will still fail until https://github.com/celestiaorg/ethermint/issues/21 is merged.

**Comment by jbowen93** [comment]
I'm not sure why various builds are failing on go module imports. The `ephemeral` job [passes on push](https://github.com/celestiaorg/ethermint/runs/5634466585?check_suite_focus=true) but [fails on pull_request](https://github.com/celestiaorg/ethermint/runs/5634466926?check_suite_focus=true).

I think this is something in how the checkout action is working with the pull request. My preference would be to merge this since everything we expect to pass is working on a local checkout.

**Review by liamsi — APPROVED** [review]
utACK

**Review by tzdybal — APPROVED** [review]
LGTM

**Pull request merged**
