### PR TITLE
Add changes to use Optimint v0.1.1

### PR DESCRIPTION
**Pull request by jbowen93**
This PR adds changes from the tzdybal/optimint branch while already being rebased on the github.com/tharsis/ethermint main branch.

It should be squashed before merging.

This has been manually tested to work with Cevmos. 

After merging a follow up commit to update the Changelog should be made and a v0.1.0 release should be cut. 

https://github.com/celestiaorg/ethermint/issues/3

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
CI failing

**Review by adlerjohn — COMMENTED** [review]
Is it possible to make all CI checks pass, or no?

**Comment by jbowen93** [comment]
> Is it possible to make all CI checks pass, or no?

Not trivially. Some of the tests assume you can start a chain w/ just the `ethermintd` binary. We need to run a cluster w/ `celestia-app`, `celestia-node`, `dalc`, and `ethermintd` to get this same state. 

Also the solidity tests are a bit of a mess. I'm almost done manually testing things and then I'll post some verification that things pass locally on the ephemeral cluster.

**Comment by jbowen93** [comment]
There are some legitimately not working RPC Tests: https://github.com/celestiaorg/ethermint/issues/7 and the solidity tests should probably be redone.

**Review by adlerjohn — APPROVED** [review]
utACK

**Review by tzdybal — APPROVED** [review]
LGTM (especially the Optimint-related changes)

**Pull request merged**
