### PR TITLE
feat: use optimint v0.2.0

### PR DESCRIPTION
**Pull request by tzdybal**

### CODE REVIEW

**Review by adlerjohn — DISMISSED** [review]
ci failing

**Comment by jbowen93** [comment]
utACK. Just need to run `gofmt` on the two go files.

**Comment by jbowen93** [comment]
Premature conversion out of Draft. My apologies. I think there are changes needed to the testutil code.

**Comment by jbowen93** [comment]
Tests are flakey 🙃 but now they're green.

We don't care about semgrep right now.

**Review by jbowen93 — APPROVED** [review]

**Pull request merged**
